"use client";
import { useCallback, useEffect, useRef, useState } from "react";

type Reply = { id:string; author:string; role:string; body:string; created_at:string };
type Thread = { id:string; trade:string; author:string; subject:string; body:string; created_at:string; replies:Reply[]; canDelete?:boolean };
export default function FieldBoard({endpoint,admin,enabled,onSeen}:{endpoint:string;admin:boolean;enabled:boolean;onSeen?:()=>void}) {
 const onSeenRef=useRef(onSeen); onSeenRef.current=onSeen;
 const [remoteEnabled,setRemoteEnabled]=useState(enabled),[showQuestion,setShowQuestion]=useState(false);
 const [answering,setAnswering]=useState<string|null>(null);
 const [threads,setThreads]=useState<Thread[]>([]),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[reply,setReply]=useState<Record<string,string>>({}),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async(q:string)=>{try{const res=await fetch(`${endpoint}?q=${encodeURIComponent(q)}`,{cache:"no-store"});const data: any=await res.json();if(!res.ok)throw new Error(data.error||"Could not load questions");setThreads(data.threads||[]);if(!admin)setRemoteEnabled(data.enabled!==false);}catch(e){setNotice(e instanceof Error?e.message:"Could not load questions");}},[endpoint,admin]);
 useEffect(()=>{void load(search);if(admin){void fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"seen"})}).then(()=>onSeenRef.current?.()).catch(()=>{});}},[admin,endpoint,load,search]);
 async function post(payload:Record<string,string>){setBusy(true);setNotice("");try{const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data: any=await res.json();if(!res.ok)throw new Error(data.error||"Could not save");setSubject("");setBody("");setReply({});if(payload.action==="ask")setShowQuestion(false);if(payload.action==="reply")setAnswering(null);setNotice(payload.action==="ask"?(admin?"Question posted to your trade board.":"Question posted. Your supervisor has a notification."):payload.action==="delete"?"Question deleted.":"Answer posted.");await load(search);}catch(e){setNotice(e instanceof Error?e.message:"Could not save");}finally{setBusy(false);}}
 return <div className="field-board">{notice&&<p className="notice" role="status">{notice}</p>}{!admin&&!remoteEnabled?<section className="card"><h2>Field questions are off</h2><p>Your supervisor can turn this feature on for the company.</p></section>:<>
 <form className="search-row" onSubmit={e=>{e.preventDefault();setSearch(query.trim());}}><input aria-label="Search field questions" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a problem, question, or answer"/><button className="secondary">Search</button>{search&&<button type="button" className="quiet" onClick={()=>{setQuery("");setSearch("");}}>Clear</button>}</form>
 <div className="board-ask-action"><button type="button" className="primary" onClick={()=>setShowQuestion(!showQuestion)}>{showQuestion?"Cancel question":"+ Post question"}</button></div>
 {showQuestion&&<section className="card narrow"><h2>Ask the trade board</h2><p>Techs at other companies in your trade can read this. Leave out customer names, addresses, and private job details.</p><label>Short question<input value={subject} maxLength={160} onChange={e=>setSubject(e.target.value)} placeholder="Example: Why is the high water alarm coming on?"/></label><label>What have you checked?<textarea rows={4} value={body} maxLength={3000} onChange={e=>setBody(e.target.value)} placeholder="Share the system type, symptoms, and checks so far."/></label><button type="button" className="primary" disabled={busy||!subject.trim()||!body.trim()} onClick={()=>void post({action:"ask",subject,body})}>Post to board</button></section>}

 <h2 className="below">{search?"Search results":"Recent field questions"}</h2><div className="list">{threads.map(t=><article className="card board-thread" key={t.id}><div className="eyebrow">{t.trade} · {new Date(t.created_at).toLocaleString()}</div><h2>{t.subject}</h2><p>{t.body}</p><small>Asked by {t.author}</small><div className="board-replies">{t.replies.map(r=><div className="board-reply" key={r.id}><strong>{r.author}{r.role==="admin"?" · Supervisor":""}</strong><small>{new Date(r.created_at).toLocaleString()}</small><p>{r.body}</p></div>)}</div><div className="board-thread-actions"><button type="button" className="secondary" onClick={()=>setAnswering(answering===t.id?null:t.id)}>{answering===t.id?"Cancel answer":"Answer"}</button>{admin&&t.canDelete&&<button type="button" className="quiet" disabled={busy} onClick={()=>{if(window.confirm("Delete this question and its answers from the trade board?"))void post({action:"delete",threadId:t.id});}}>Delete question</button>}</div>{answering===t.id&&<div className="board-answer-form"><label>Your answer<textarea rows={3} value={reply[t.id]||""} maxLength={3000} onChange={e=>setReply({...reply,[t.id]:e.target.value})} placeholder="Share what you would check or how you solved it."/></label><button type="button" className="primary" disabled={busy||!reply[t.id]?.trim()} onClick={()=>void post({action:"reply",threadId:t.id,body:reply[t.id]})}>Post answer</button></div>}</article>)}{!threads.length&&<div className="empty"><h2>No questions found</h2><p>{search?"Try a different search or ask the crew.":"The first field question will appear here."}</p></div>}</div></>}</div>;
}
