"use client";
import { useEffect, useState } from "react";
type Data={company:string;logo?:string;lessons:Array<{id:string;title:string;status:string;summary:string;content:string;slides?:Array<{title:string;bullets:string[]}>;questions?:string[]}>;policies:Array<{id:string;title:string;body:string;attachments?:Array<{id:string;name:string;data:string}>}>;lessonAccess:Array<{techId:string;lessonId:string;availableAt:string}>;completions:Array<{techId:string;courseName:string;completedDate:string}>;yearsBusiness?:string;services?:string;companyLicenses?:string;serviceAreas?:string;achievements?:string;projects?:string};
type Tech={id:string;name:string;email:string;phone:string;title?:string;trade:string;years?:string;background?:string;licenses?:Array<{name:string;number:string}>};
export default function ManagerWorkspace(){const [page,setPage]=useState("Overview"),[data,setData]=useState<Data|null>(null),[techs,setTechs]=useState<Tech[]>([]),[selected,setSelected]=useState<string|null>(null),[acks,setAcks]=useState<Array<{invite_id:string;policy_id:string;acknowledged_at:string}>>([]),[progress,setProgress]=useState<Array<{techId:string;lessonId:string;answers:string[];updatedAt:string}>>([]),[error,setError]=useState("");useEffect(()=>{fetch("/api/admin/workspace",{cache:"no-store"}).then(async r=>{const j:any=await r.json();if(!r.ok)throw new Error(j.error||"Could not load workspace");setData(j.data);setTechs(j.techs||[]);setAcks(j.policyAcknowledgments||[]);setProgress(j.progress||[]);}).catch(e=>setError(e.message));},[]);const menus=["Overview","Technicians","Lessons","Field questions","Policies","Company profile","Settings"];return <div className="shell"><aside className="rail"><div className="brand"><div className="brandmark">{data?.logo?<img src={data.logo} alt=""/>:"F+"}</div><div><strong>Fieldcraft</strong><small>TRAINING WORKSPACE</small></div></div><div className="company-name">{data?.company||"Company"}</div><div className="rail-label">MANAGER · READ ONLY</div><nav>{menus.map(m=><button key={m} className={page===m?"active":""} onClick={()=>{setPage(m);setSelected(null);}}>{m}</button>)}</nav></aside><main className="main"><header className="top"><div className="crumb">Manager workspace / {page}</div></header><div className="body">{error&&<p className="validation">{error}</p>}{!data&&!error&&<p>Loading workspace…</p>}{data&&<>
 {page==="Overview"&&<><div className="heading"><div><div className="eyebrow">READ ONLY</div><h1>{data.company}</h1><p>View your company training records.</p></div></div><div className="stats"><div><b>{data.lessons?.length||0}</b><span>Lessons</span></div><div><b>{techs.length}</b><span>Technicians</span></div><div><b>{data.policies?.length||0}</b><span>Policies</span></div></div></>}
 {page==="Technicians"&&<><h1>Technicians</h1><div className="list">{techs.map(t=><article className="card" key={t.id}><button className="quiet" onClick={()=>setSelected(selected===t.id?null:t.id)}>{t.name} · {t.trade} · View profile</button>{selected===t.id&&<><p>{t.email} · {t.phone}</p><p>{t.years||"0"} years of experience</p><p>{t.background}</p><h3>Licenses</h3>{t.licenses?.map((l,i)=><p key={i}>{l.name} · {l.number}</p>)}<h3>Assigned lessons</h3>{data.lessonAccess?.filter(a=>a.techId===t.id).map(a=><p key={a.lessonId}>{data.lessons.find(l=>l.id===a.lessonId)?.title||"Lesson"} · Opens {new Date(a.availableAt).toLocaleString()}</p>)}<h3>Submitted answers</h3>{progress.filter(a=>a.techId===t.id).map(a=><div key={a.lessonId}><strong>{data.lessons.find(l=>l.id===a.lessonId)?.title||"Lesson"}</strong>{a.answers.map((answer,i)=><p key={i}>{i+1}. {answer}</p>)}</div>)}<h3>Completed courses</h3>{data.completions?.filter(c=>c.techId===t.id).map((c,i)=><p key={i}>{c.courseName} · {c.completedDate}</p>)}</>}</article>)}</div></>}
 {page==="Lessons"&&<><h1>Lessons</h1><div className="list">{data.lessons?.map(l=><article className="card" key={l.id}><button className="quiet" onClick={()=>setSelected(selected===l.id?null:l.id)}>{l.title} · {l.status} · View</button>{selected===l.id&&<><p>{l.summary}</p><p className="policy-body">{l.content}</p>{l.slides?.map((s,i)=><div key={i}><h3>{s.title}</h3><ul>{s.bullets.map((b,n)=><li key={n}>{b}</li>)}</ul></div>)}<h3>Questions</h3>{l.questions?.map((q,i)=><p key={i}>{i+1}. {q}</p>)}<h3>Files</h3>{(l as typeof l&{attachments?:Array<{id:string;name:string;data:string}>}).attachments?.map(f=><p key={f.id}><a href={f.data} download={f.name}>{f.name}</a></p>)}<h3>Assigned technicians</h3>{data.lessonAccess?.filter(a=>a.lessonId===l.id).map(a=><p key={a.techId}>{techs.find(t=>t.id===a.techId)?.name||"Technician"} · {new Date(a.availableAt).toLocaleString()}</p>)}</>}</article>)}</div></>}
 {page==="Policies"&&<><h1>Company policies</h1>{data.policies?.map(p=><article className="card below" key={p.id}><h2>{p.title}</h2><p className="policy-body">{p.body}</p>{p.attachments?.map(f=><p key={f.id}><a href={f.data} download={f.name}>{f.name}</a></p>)}<h3>Read acknowledgments</h3>{acks.filter(a=>a.policy_id===p.id).map(a=><p key={a.invite_id}>{techs.find(t=>t.id===a.invite_id)?.name||"Technician"} · {new Date(a.acknowledged_at).toLocaleString()}</p>)}</article>)}</>}
 {page==="Field questions"&&<ManagerBoard/>}
 {page==="Company profile"&&<><h1>{data.company}</h1><div className="card">{(["yearsBusiness","services","companyLicenses","serviceAreas","achievements","projects"] as const).map(k=><p key={k}><strong>{k.replace(/([A-Z])/g," $1")}</strong><br/>{data[k]||"—"}</p>)}</div></>}
 {page==="Settings"&&<><h1>Settings</h1><p>Manager access is read only. Ask the owner to change company or staff settings.</p></>}
 </>}</div></main></div>}
function ManagerBoard(){const [threads,setThreads]=useState<Array<{id:string;subject:string;body:string;author:string;replies:Array<{id:string;author:string;body:string}>}>>([]);useEffect(()=>{fetch("/api/admin/field-questions",{cache:"no-store"}).then(r=>r.json()).then((j:any)=>setThreads(j.threads||[])).catch(()=>{});},[]);return <><h1>Field questions</h1><p>Read only view of your trade board.</p><div className="list">{threads.map(t=><article className="card" key={t.id}><h2>{t.subject}</h2><p>{t.body}</p><small>Asked by {t.author}</small>{t.replies.map(r=><div className="board-reply" key={r.id}><strong>{r.author}</strong><p>{r.body}</p></div>)}</article>)}</div></>}
