"use client";
import { useState } from "react";
export type PolicyFile={id:string;name:string;mime:string;data:string;size:number};
export type CompanyPolicy={id:string;title:string;body:string;attachments?:PolicyFile[]};
export default function PolicyManager({policies,onChange,onTalk,acknowledgments,techs}:{policies:CompanyPolicy[];onChange:(policies:CompanyPolicy[])=>void;onTalk:(policy:CompanyPolicy)=>void;acknowledgments:Array<{invite_id:string;policy_id:string;acknowledged_at:string}>;techs:Array<{id:string;name:string}>}) {
 const [title,setTitle]=useState(""),[body,setBody]=useState(""),[files,setFiles]=useState<PolicyFile[]>([]),[error,setError]=useState("");
 async function addFiles(input:FileList|null){if(!input)return;const next:PolicyFile[]=[];for(const file of Array.from(input)){if(!/^(application\/pdf|text\/plain|image\/(png|jpeg|webp)|application\/(msword|vnd.openxmlformats-officedocument.wordprocessingml.document))$/.test(file.type)){setError(`Unsupported file: ${file.name}`);continue;}if(file.size>1500000){setError(`File must be under 1.5 MB: ${file.name}`);continue;}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);}).catch(()=>"");if(data)next.push({id:crypto.randomUUID(),name:file.name,mime:file.type,data,size:file.size});}if([...files,...next].reduce((n,f)=>n+f.size,0)>2500000){setError("Keep files for one policy under 2.5 MB total.");return;}setFiles([...files,...next]);}
 function save(){if(!title.trim()||(!body.trim()&&!files.length)){setError("Add a title and policy text or a file.");return;}onChange([...policies,{id:crypto.randomUUID(),title:title.trim(),body:body.trim(),attachments:files}]);setTitle("");setBody("");setFiles([]);setError("");}
 return <><div className="heading"><div><div className="eyebrow">COMPANY PRIVATE</div><h1>Company policies</h1><p>Publish your rules for your technicians to read and acknowledge. Policy Talks are private lessons for your crew.</p></div></div><section className="card narrow"><h2>Add a policy</h2><label>Policy title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Example: Job site safety"/></label><label>Policy details<textarea rows={6} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write the rule your crew needs to follow."/></label><label className="upload-label">+ Upload policy files<input type="file" multiple accept=".pdf,.txt,.doc,.docx,.png,.jpg,.jpeg,.webp" onChange={e=>{void addFiles(e.target.files);e.target.value="";}}/></label>{files.map(f=><div className="policy-file" key={f.id}>{f.name} <button className="quiet" onClick={()=>setFiles(files.filter(x=>x.id!==f.id))}>Remove</button></div>)}{error&&<p className="validation" role="alert">{error}</p>}<div className="actions below"><button className="primary" onClick={save}>Add policy</button></div><p className="hint">Each file may be up to 1.5 MB. Policies stay with this company.</p></section><div className="list below">{policies.map(p=><article className="card" key={p.id}><h2>{p.title}</h2>{p.body&&<p className="policy-body">{p.body}</p>}{p.attachments?.map(f=><p key={f.id}><a href={f.data} download={f.name}>{f.name}</a></p>)}<p className="hint">Read and accepted: {acknowledgments.filter(a=>a.policy_id===p.id).length} of {techs.length} technicians</p>{acknowledgments.filter(a=>a.policy_id===p.id).map(a=><p className="hint" key={a.invite_id}>{techs.find(t=>t.id===a.invite_id)?.name||"Technician"} · {new Date(a.acknowledged_at).toLocaleString()}</p>)}<div className="actions"><button className="secondary" onClick={()=>onTalk(p)}>+ Create Policy Talk</button><button className="quiet" onClick={()=>{if(window.confirm("Remove this company policy?"))onChange(policies.filter(x=>x.id!==p.id));}}>Remove policy</button></div></article>)}{!policies.length&&<div className="empty"><h2>No policies added yet</h2><p>Add your first company rule or upload a policy file.</p></div>}</div></>;
}
