"use client";
import { useEffect, useState } from "react";

type Staff={id:string;email:string;name:string;role:"manager"|"trainer";invite_token:string;expires_at:string;accepted_at:string|null};
export default function StaffSettings(){
 const [staff,setStaff]=useState<Staff[]>([]),[name,setName]=useState(""),[email,setEmail]=useState(""),[role,setRole]=useState<"manager"|"trainer">("trainer"),[notice,setNotice]=useState("");
 const [invitation,setInvitation]=useState<{name:string;email:string;role:string;token:string}|null>(null);
 async function load(){const r=await fetch("/api/admin/staff",{cache:"no-store"});const j:any=await r.json();if(r.ok)setStaff(j.staff||[]);else setNotice(j.error||"Could not load team");}
 useEffect(()=>{void load();},[]);
 async function save(action?:string,id?:string){const invitedName=name,invitedEmail=email,invitedRole=role;const r=await fetch("/api/admin/staff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action?{action,id}:{name,email,role})});const j:any=await r.json();if(!r.ok){setNotice(j.error||"Could not save");return;}if(action==="remove"){setInvitation(null);setNotice("Access removed.");}else if(action==="resend"){const person=staff.find(s=>s.id===id);if(person&&j.inviteToken)setInvitation({name:person.name,email:person.email,role:person.role,token:j.inviteToken});setNotice("New invitation link ready below.");}else{setInvitation({name:invitedName,email:invitedEmail,role:invitedRole,token:j.inviteToken});setName("");setEmail("");setNotice("Invitation link ready below. Copy and send it by text.");}await load();}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice("Copied. Paste it into a text message.");}catch{setNotice("Select and copy the text below.");}}
 const inviteLink=invitation?`${typeof location!=="undefined"?location.origin:""}/staff/${invitation.token}`:"";
 const message=invitation?`Hi ${invitation.name}, you've been invited as a ${invitation.role} to our Fieldcraft training workspace. Open this link, sign in, and fill out your staff profile to accept: ${inviteLink}`:"";
 return <section className="card below"><h2>Add managers and trainers</h2><p>Managers can read the workspace. Trainers can manage training. Company details and staff access stay with the owner.</p><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email (optional)<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Access<select value={role} onChange={e=>setRole(e.target.value as "manager"|"trainer")}><option value="trainer">Trainer</option><option value="manager">Manager · read only</option></select></label></div><button className="primary" disabled={!name.trim()} onClick={()=>void save()}>Create invitation link</button>{notice&&<p role="status">{notice}</p>}
 {invitation&&<div className="staff-invite-result"><h3>Invitation for {invitation.name}</h3><p>Send this by text. {invitation.email?<>The invited person signs in using <strong>{invitation.email}</strong>.</>:"They will enter their email when they accept the invitation."}</p><label>Copy link<input readOnly value={inviteLink} onFocus={e=>e.target.select()}/></label><button className="primary" onClick={()=>void copy(inviteLink)}>Copy invitation link</button><label>Ready-to-send text<textarea readOnly rows={4} value={message} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={()=>void copy(message)}>Copy text message</button><p className="hint">The link expires in 7 days. You can make a new one below.</p></div>}
 <h3 className="below">Your team</h3><div className="list">{staff.map(s=><div className="policy" key={s.id}><div><strong>{s.name}</strong><p>{s.email||"Email added by invitee"} · {s.role} · {s.accepted_at?"Active":new Date(s.expires_at).getTime()<Date.now()?"Invitation expired":"Invitation pending"}</p></div><div className="actions">{!s.accepted_at&&<><button className="secondary" onClick={()=>{setInvitation({name:s.name,email:s.email,role:s.role,token:s.invite_token});setNotice("Invitation link ready above.");}}>Show invitation link</button><button className="quiet" onClick={()=>void save("resend",s.id)}>New link</button></>}<button className="quiet" onClick={()=>{if(window.confirm(`Remove ${s.name}'s access?`))void save("remove",s.id);}}>Remove</button></div></div>)}</div></section>;
}
